// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlrf871oqd9teJNEehMx_4P5iCpk3SH2E',
    appId: '1:849765276764:web:0441ed9440be1da58d5a99',
    messagingSenderId: '849765276764',
    projectId: 'final-exam-b2fb7',
    authDomain: 'final-exam-b2fb7.firebaseapp.com',
    storageBucket: 'final-exam-b2fb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPNYxXwBCCD34i55eS404RzswDE8_F5Vk',
    appId: '1:849765276764:android:50b8b667f650a8c68d5a99',
    messagingSenderId: '849765276764',
    projectId: 'final-exam-b2fb7',
    storageBucket: 'final-exam-b2fb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCns1j7EYwx6HEq6_n6ReFLKxwQCVpTWgI',
    appId: '1:849765276764:ios:1da30be14dba2f028d5a99',
    messagingSenderId: '849765276764',
    projectId: 'final-exam-b2fb7',
    storageBucket: 'final-exam-b2fb7.appspot.com',
    iosBundleId: 'com.example.advFlutterFinalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCns1j7EYwx6HEq6_n6ReFLKxwQCVpTWgI',
    appId: '1:849765276764:ios:1da30be14dba2f028d5a99',
    messagingSenderId: '849765276764',
    projectId: 'final-exam-b2fb7',
    storageBucket: 'final-exam-b2fb7.appspot.com',
    iosBundleId: 'com.example.advFlutterFinalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlrf871oqd9teJNEehMx_4P5iCpk3SH2E',
    appId: '1:849765276764:web:0c170e5a7db05d858d5a99',
    messagingSenderId: '849765276764',
    projectId: 'final-exam-b2fb7',
    authDomain: 'final-exam-b2fb7.firebaseapp.com',
    storageBucket: 'final-exam-b2fb7.appspot.com',
  );
}
